#!/bin/bash
echo "Content-type:text/text"
echo ""
read POST_STRING
TOKEN=$(echo "${POST_STRING}" | grep '^TOKEN=[a-zA-Z0-9+_]*$' | sed 's|^TOKEN=||')
if [ "${TOKEN}" != "" ] ; then
 echo "${TOKEN}" | openssl enc -e -a -base64 -aes-256-cbc -salt -pass file:/data/secrets/github_hook_secret
else
  echo "Invalid/Missing TOKEN sent"
fi
