#!/usr/bin/env python
import cgi;

print "Content-type: text/plain\n"

form = cgi.FieldStorage();

production = "type=Production;"
if ("anytype" in form) and form["anytype"].value=="1":
  production=""

announced="state=Announced;"
if ("deprel" in form) and form["deprel"].value=="1":
  announced="state=Deprecated;"
  
architecture=""
if "architecture" in form:
  architecture="architecture="+form["architecture"].value+";"

releases_filename = "/data/sdt/SDT/releases.map"
releases_file = open(releases_filename, "r")

archs = {}
rels  = []
for line in releases_file:
  if 'prodarch=1;' not in line: continue
  if production   and production   not in line: continue
  if announced    and announced    not in line: continue
  if architecture and architecture not in line: continue
  data = {}
  for item in line.split(";"):
    if "=" not in item: continue
    k,v = item.split("=")
    data[k]= v
  if ("architecture" in data) and ("label" in data) and ("type" in data) and ("state" in data):
    if data["label"] in rels: continue
    rels.append(data["label"])
    arch = data["architecture"]
    if arch not in archs: archs[arch]=[]
    archs[arch].append("""<project label="%(label)s" type="%(type)s" state="%(state)s"/>""" % data)
    
releases_file.close()

print "<projects>"
for arch in archs:
  print """  <architecture name="%s">""" % arch
  for rel in archs[arch]:
    print "    "+rel
  print "  </architecture>"
print "</projects>"
